import React, { useContext } from 'react';
import { Link } from 'react-router-dom';
import { AuthContext } from '../App';
import { 
  Brain, 
  Image, 
  FileText, 
  Target, 
  Trophy, 
  BarChart3, 
  Zap,
  Timer,
  Users,
  Puzzle,
  PenTool,
  Volume2,
  ShieldCheck
} from 'lucide-react';

const Dashboard = () => {
  const { user } = useContext(AuthContext);

  const games = [
    {
      id: 'ai-image',
      title: 'AI Image Detection',
      description: 'Can you spot the difference between AI-generated and real images? Test your visual perception against advanced AI models.',
      icon: Image,
      route: '/game/ai-image',
      difficulty: 'Medium',
      estimatedTime: '5-10 min',
      color: 'from-blue-500 to-cyan-500'
    },
    {
      id: 'text-ai',
      title: 'Text or AI',
      description: 'Identify whether text snippets were written by humans or AI. Challenge your language intuition.',
      icon: FileText,
      route: '/game/text-ai',
      difficulty: 'Hard',
      estimatedTime: '8-12 min',
      color: 'from-purple-500 to-pink-500'
    },
    {
      id: 'memory',
      title: 'Memory Challenge',
      description: 'Remember and recall number sequences. Compare your memory capacity with AI systems.',
      icon: Target,
      route: '/game/memory',
      difficulty: 'Easy',
      estimatedTime: '3-7 min',
      color: 'from-green-500 to-emerald-500'
    },
    {
      id: 'logical-reasoning',
      title: 'Logical Reasoning',
      description: 'Solve number sequences, pattern puzzles, and logic problems. Challenge your analytical thinking against AI logic.',
      icon: Puzzle,
      route: '/game/logical-reasoning',
      difficulty: 'Medium',
      estimatedTime: '4-8 min',
      color: 'from-indigo-500 to-purple-500'
    },
    {
      id: 'creative-writing',
      title: 'Creative Writing',
      description: 'Write creative stories and poems from prompts. Compare your imagination and writing style with AI creativity.',
      icon: PenTool,
      route: '/game/creative-writing',
      difficulty: 'Hard',
      estimatedTime: '10-15 min',
      color: 'from-purple-500 to-pink-500'
    },
    {
      id: 'audio-recognition',
      title: 'Audio Recognition',
      description: 'Listen to audio clips and identify whether they were created by humans or generated by AI. Test your auditory perception.',
      icon: Volume2,
      route: '/game/audio-recognition',
      difficulty: 'Medium',
      estimatedTime: '6-10 min',
      color: 'from-green-500 to-teal-500'
    }
  ];

  const tools = [
    {
      id: 'content-auth',
      title: 'Content Authentication',
      description: 'Upload images to detect if they are authentic or AI-generated. Advanced detection using state-of-the-art models.',
      icon: ShieldCheck,
      route: '/content-authentication',
      category: 'Detection Tool',
      color: 'from-blue-500 to-indigo-500'
    }
  ];

  return (
    <div className="min-h-screen bg-slate-950">
      {/* Navigation */}
      <nav className="navbar">
        <div className="nav-content">
          <Link to="/dashboard" className="nav-brand">
            CognitiveArena
          </Link>
          <div className="nav-links">
            <Link to="/dashboard" className="nav-link active">
              Dashboard
            </Link>
            <Link to="/leaderboard" className="nav-link">
              Leaderboard
            </Link>
            <Link to="/stats" className="nav-link">
              Stats
            </Link>
            {/* Auth removed: open access */}
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-4 py-8">
        {/* Welcome Section */}
        <div className="mb-12">
          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold text-white mb-4">
              Welcome back, <span className="bg-gradient-to-r from-cyan-400 to-purple-500 bg-clip-text text-transparent">{user?.username}</span>
            </h1>
            <p className="text-xl text-slate-400">Ready to challenge AI in cognitive tasks?</p>
          </div>

          {/* User Stats Quick View */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-12">
            <div className="bg-slate-800/50 backdrop-blur-sm rounded-xl p-6 border border-slate-700">
              <div className="flex items-center gap-3 mb-2">
                <Trophy className="w-6 h-6 text-yellow-400" />
                <span className="text-slate-400">Total Games</span>
              </div>
              <div className="text-2xl font-bold text-white">{user?.total_games_played || 0}</div>
            </div>
            <div className="bg-slate-800/50 backdrop-blur-sm rounded-xl p-6 border border-slate-700">
              <div className="flex items-center gap-3 mb-2">
                <Zap className="w-6 h-6 text-cyan-400" />
                <span className="text-slate-400">Total Score</span>
              </div>
              <div className="text-2xl font-bold text-white">{user?.total_score || 0}</div>
            </div>
            <div className="bg-slate-800/50 backdrop-blur-sm rounded-xl p-6 border border-slate-700">
              <div className="flex items-center gap-3 mb-2">
                <Target className="w-6 h-6 text-green-400" />
                <span className="text-slate-400">Avg Accuracy</span>
              </div>
              <div className="text-2xl font-bold text-white">
                {user?.total_games_played > 0 ? '85%' : '0%'}
              </div>
            </div>
            <div className="bg-slate-800/50 backdrop-blur-sm rounded-xl p-6 border border-slate-700">
              <div className="flex items-center gap-3 mb-2">
                <Users className="w-6 h-6 text-purple-400" />
                <span className="text-slate-400">Rank</span>
              </div>
              <div className="text-2xl font-bold text-white">
                {user?.total_games_played > 0 ? '#42' : 'Unranked'}
              </div>
            </div>
          </div>
        </div>

        {/* Games Section */}
        <div className="mb-12">
          <div className="flex justify-between items-center mb-8">
            <h2 className="text-3xl font-bold text-white">Cognitive Challenges</h2>
            <Link 
              to="/leaderboard" 
              className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg transition-colors"
            >
              <Trophy className="w-4 h-4" />
              View Leaderboard
            </Link>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {games.map((game) => (
              <div key={game.id} className="game-card group">
                <div className="relative z-10">
                  <div className={`inline-flex p-4 rounded-2xl bg-gradient-to-r ${game.color} bg-opacity-20 mb-6`}>
                    <game.icon className="w-8 h-8 text-white" />
                  </div>
                  
                  <h3 className="game-title">{game.title}</h3>
                  <p className="game-description">{game.description}</p>
                  
                  <div className="flex items-center gap-4 mb-6">
                    <div className="flex items-center gap-2 text-slate-400 text-sm">
                      <Timer className="w-4 h-4" />
                      {game.estimatedTime}
                    </div>
                    <div className={`px-3 py-1 rounded-full text-xs font-medium ${
                      game.difficulty === 'Easy' ? 'bg-green-500/20 text-green-400' :
                      game.difficulty === 'Medium' ? 'bg-yellow-500/20 text-yellow-400' :
                      'bg-red-500/20 text-red-400'
                    }`}>
                      {game.difficulty}
                    </div>
                  </div>
                  
                  <Link 
                    to={game.route}
                    className="game-play-btn w-full justify-center"
                  >
                    <Brain className="w-5 h-5" />
                    Start Challenge
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Tools Section */}
        <div className="mb-12">
          <div className="flex justify-between items-center mb-8">
            <h2 className="text-3xl font-bold text-white">Detection Tools</h2>
            <div className="flex items-center gap-2 px-4 py-2 bg-slate-800 text-slate-300 rounded-lg">
              <ShieldCheck className="w-4 h-4" />
              AI Detection
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {tools.map((tool) => (
              <div key={tool.id} className="game-card group">
                <div className="relative z-10">
                  <div className={`inline-flex p-4 rounded-2xl bg-gradient-to-r ${tool.color} bg-opacity-20 mb-6`}>
                    <tool.icon className="w-8 h-8 text-white" />
                  </div>
                  
                  <h3 className="game-title">{tool.title}</h3>
                  <p className="game-description">{tool.description}</p>
                  
                  <div className="flex items-center gap-4 mb-6">
                    <div className={`px-3 py-1 rounded-full text-xs font-medium bg-blue-500/20 text-blue-400`}>
                      {tool.category}
                    </div>
                  </div>
                  
                  <Link 
                    to={tool.route}
                    className="game-play-btn w-full justify-center"
                  >
                    <ShieldCheck className="w-5 h-5" />
                    Use Tool
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* AI Performance Insight */}
        <div className="bg-gradient-to-r from-slate-800/50 to-slate-900/50 backdrop-blur-sm rounded-2xl p-8 border border-slate-700">
          <div className="flex items-center gap-3 mb-6">
            <BarChart3 className="w-6 h-6 text-cyan-400" />
            <h3 className="text-2xl font-bold text-white">AI Performance Baseline</h3>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="text-3xl font-bold text-cyan-400 mb-2">92.5%</div>
              <div className="text-slate-300 font-medium">AI Image Detection</div>
              <div className="text-sm text-slate-500">Average AI accuracy</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-purple-400 mb-2">88.7%</div>
              <div className="text-slate-300 font-medium">Text Analysis</div>
              <div className="text-sm text-slate-500">Average AI accuracy</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-green-400 mb-2">78.3%</div>
              <div className="text-slate-300 font-medium">Memory Tasks</div>
              <div className="text-sm text-slate-500">Average AI accuracy</div>
            </div>
          </div>
          
          <div className="mt-6 text-center">
            <p className="text-slate-400">
              These are the baselines you're competing against. Can human intuition beat artificial intelligence?
            </p>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="mt-12 text-center">
          <h3 className="text-xl font-bold text-white mb-6">Quick Actions</h3>
          <div className="flex justify-center gap-4">
            <Link 
              to="/stats" 
              className="flex items-center gap-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg transition-colors"
            >
              <BarChart3 className="w-4 h-4" />
              View Detailed Stats
            </Link>
            <Link 
              to="/leaderboard" 
              className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-cyan-500 to-purple-600 text-white rounded-lg hover:shadow-lg transition-all"
            >
              <Trophy className="w-4 h-4" />
              Global Leaderboard
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;